### ISSUE TITLE
Handling of XML namespaces in PROPFIND responds

### ISSUE THREAD

**Issue by telkamp** [designerror/webdav-client-cpp#17]
Having a QNAP NAS as WebDAV server where Apache is installed.
PROPFIND requests returns a respond like this:
   [...]
   <D:response xmlns:lp1="DAV:">
   <D:href>/temp/dir_with_files_and_dirs/</D:href>
   <D:propstat>
   <D:prop>
   <lp1:resourcetype><D:collection/></lp1:resourcetype>
   </D:prop>
   [...]
So we get "D" instead of "d" and "lp1:resourcetype" instead of "d:resourcetype"
This is not handled correctly by webdav-client-cpp, e.g. in the ::info method.
For an example of a PROPFIND respond see also http://people.apache.org/~thorsten/proposal/docs/components/repository/webdav.html

Nice code example here: https://stackoverflow.com/questions/21162186/pugixml-parse-namespace-with-prefix-mapping-and-without-prefix-mappig

**Comment by rusdevops** [comment]
@telkamp, Thanks for the comment, soon we will solve this issue.
