### ISSUE TITLE
::list returns the name of the root directory

### ISSUE THREAD

**Issue by telkamp** [designerror/webdav-client-cpp#19]
I'm not sure if this is an issue of the ::list method or the tests.
The tests checking the number of directory entries fails, because I'm getting 1 directory more than expected. E.g. tests/list.cpp returns 11 entries, and 10 is the expected value:
   /temp/dir_with_files_and_dirs/
   /temp/dir_with_files_and_dirs/file5
   /temp/dir_with_files_and_dirs/file2
   /temp/dir_with_files_and_dirs/file4
   /temp/dir_with_files_and_dirs/dir1/
   /temp/dir_with_files_and_dirs/dir4/
   /temp/dir_with_files_and_dirs/dir3/
   /temp/dir_with_files_and_dirs/file1
   /temp/dir_with_files_and_dirs/dir5/
   /temp/dir_with_files_and_dirs/dir2/
   /temp/dir_with_files_and_dirs/file3

**Comment by rusdevops** [comment]
@telkamp, Thanks for the comment, soon we will solve this issue.
